#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Generated Thu Oct 12 01:57:52 2017 by generateDS.py version 2.28b.
# Python 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]
#
# Command line options:
#   ('--silence', '')
#   ('--external-encoding', 'utf-8')
#   ('-o', '../dsr-xml-validation/dsoh.py')
#   ('-s', '../dsr-xml-validation/dsohsubs.py')
#
# Command line arguments:
#   ../dsr-xml-validation/Dealer Stock On Hand.xsd
#
# Command line:
#   generateDS.py --silence --external-encoding="utf-8" -o "../dsr-xml-validation/dsoh.py" -s "../dsr-xml-validation/dsohsubs.py" ../dsr-xml-validation/Dealer Stock On Hand.xsd
#
# Current working directory (os.getcwd()):
#   generateDS
#

import sys
import re as re_
import base64
import datetime as datetime_
import warnings as warnings_
try:
    from lxml import etree as etree_
except ImportError:
    from xml.etree import ElementTree as etree_


Validate_simpletypes_ = True
if sys.version_info.major == 2:
    BaseStrType_ = basestring
else:
    BaseStrType_ = str


def parsexml_(infile, parser=None, **kwargs):
    if parser is None:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        #   we ignore comments.
        try:
            parser = etree_.ETCompatXMLParser()
        except AttributeError:
            # fallback to xml.etree
            parser = etree_.XMLParser()
    doc = etree_.parse(infile, parser=parser, **kwargs)
    return doc

#
# Namespace prefix definition table (and other attributes, too)
#
# The module generatedsnamespaces, if it is importable, must contain
# a dictionary named GeneratedsNamespaceDefs.  This Python dictionary
# should map element type names (strings) to XML schema namespace prefix
# definitions.  The export method for any class for which there is
# a namespace prefix definition, will export that definition in the
# XML representation of that element.  See the export method of
# any generated element type class for a example of the use of this
# table.
# A sample table is:
#
#     # File: generatedsnamespaces.py
#
#     GenerateDSNamespaceDefs = {
#         "ElementtypeA": "http://www.xxx.com/namespaceA",
#         "ElementtypeB": "http://www.xxx.com/namespaceB",
#     }
#

try:
    from generatedsnamespaces import GenerateDSNamespaceDefs as GenerateDSNamespaceDefs_
except ImportError:
    GenerateDSNamespaceDefs_ = {}

#
# The root super-class for element type classes
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError as exp:
    
    class GeneratedsSuper(object):
        tzoff_pattern = re_.compile(r'(\+|-)((0\d|1[0-3]):[0-5]\d|14:00)$')
        class _FixedOffsetTZ(datetime_.tzinfo):
            def __init__(self, offset, name):
                self.__offset = datetime_.timedelta(minutes=offset)
                self.__name = name
            def utcoffset(self, dt):
                return self.__offset
            def tzname(self, dt):
                return self.__name
            def dst(self, dt):
                return None
        def gds_format_string(self, input_data, input_name=''):
            return input_data
        def gds_validate_string(self, input_data, node=None, input_name=''):
            if not input_data:
                return ''
            else:
                return input_data
        def gds_format_base64(self, input_data, input_name=''):
            return base64.b64encode(input_data)
        def gds_validate_base64(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer(self, input_data, input_name=''):
            return '%d' % input_data
        def gds_validate_integer(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_integer_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    int(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of integers')
            return values
        def gds_format_float(self, input_data, input_name=''):
            return ('%.15f' % input_data).rstrip('0')
        def gds_validate_float(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_float_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_float_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of floats')
            return values
        def gds_format_double(self, input_data, input_name=''):
            return '%e' % input_data
        def gds_validate_double(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_double_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_double_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of doubles')
            return values
        def gds_format_boolean(self, input_data, input_name=''):
            return ('%s' % input_data).lower()
        def gds_validate_boolean(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_boolean_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_boolean_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                if value not in ('true', '1', 'false', '0', ):
                    raise_parse_error(
                        node,
                        'Requires sequence of booleans '
                        '("true", "1", "false", "0")')
            return values
        def gds_validate_datetime(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_datetime(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d.%s' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        @classmethod
        def gds_parse_datetime(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            time_parts = input_data.split('.')
            if len(time_parts) > 1:
                micro_seconds = int(float('0.' + time_parts[1]) * 1000000)
                input_data = '%s.%s' % (time_parts[0], micro_seconds, )
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt
        def gds_validate_date(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_date(self, input_data, input_name=''):
            _svalue = '%04d-%02d-%02d' % (
                input_data.year,
                input_data.month,
                input_data.day,
            )
            try:
                if input_data.tzinfo is not None:
                    tzoff = input_data.tzinfo.utcoffset(input_data)
                    if tzoff is not None:
                        total_seconds = tzoff.seconds + (86400 * tzoff.days)
                        if total_seconds == 0:
                            _svalue += 'Z'
                        else:
                            if total_seconds < 0:
                                _svalue += '-'
                                total_seconds *= -1
                            else:
                                _svalue += '+'
                            hours = total_seconds // 3600
                            minutes = (total_seconds - (hours * 3600)) // 60
                            _svalue += '{0:02d}:{1:02d}'.format(
                                hours, minutes)
            except AttributeError:
                pass
            return _svalue
        @classmethod
        def gds_parse_date(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            dt = datetime_.datetime.strptime(input_data, '%Y-%m-%d')
            dt = dt.replace(tzinfo=tz)
            return dt.date()
        def gds_validate_time(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_time(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%02d:%02d:%02d' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%02d:%02d:%02d.%s' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        def gds_validate_simple_patterns(self, patterns, target):
            # pat is a list of lists of strings/patterns.  We should:
            # - AND the outer elements
            # - OR the inner elements
            found1 = True
            for patterns1 in patterns:
                found2 = False
                for patterns2 in patterns1:
                    if re_.search(patterns2, target) is not None:
                        found2 = True
                        break
                if not found2:
                    found1 = False
                    break
            return found1
        @classmethod
        def gds_parse_time(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            if len(input_data.split('.')) > 1:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt.time()
        def gds_str_lower(self, instring):
            return instring.lower()
        def get_path_(self, node):
            path_list = []
            self.get_path_list_(node, path_list)
            path_list.reverse()
            path = '/'.join(path_list)
            return path
        Tag_strip_pattern_ = re_.compile(r'\{.*\}')
        def get_path_list_(self, node, path_list):
            if node is None:
                return
            tag = GeneratedsSuper.Tag_strip_pattern_.sub('', node.tag)
            if tag:
                path_list.append(tag)
            self.get_path_list_(node.getparent(), path_list)
        def get_class_obj_(self, node, default_class=None):
            class_obj1 = default_class
            if 'xsi' in node.nsmap:
                classname = node.get('{%s}type' % node.nsmap['xsi'])
                if classname is not None:
                    names = classname.split(':')
                    if len(names) == 2:
                        classname = names[1]
                    class_obj2 = globals().get(classname)
                    if class_obj2 is not None:
                        class_obj1 = class_obj2
            return class_obj1
        def gds_build_any(self, node, type_name=None):
            return None
        @classmethod
        def gds_reverse_node_mapping(cls, mapping):
            return dict(((v, k) for k, v in mapping.iteritems()))
        @staticmethod
        def gds_encode(instring):
            if sys.version_info.major == 2:
                return instring.encode(ExternalEncoding)
            else:
                return instring
        @staticmethod
        def convert_unicode(instring):
            if isinstance(instring, str):
                result = quote_xml(instring)
            elif sys.version_info.major == 2 and isinstance(instring, unicode):
                result = quote_xml(instring).encode('utf8')
            else:
                result = GeneratedsSuper.gds_encode(str(instring))
            return result
        def __eq__(self, other):
            if type(self) != type(other):
                return False
            return self.__dict__ == other.__dict__
        def __ne__(self, other):
            return not self.__eq__(other)
    
    def getSubclassFromModule_(module, class_):
        '''Get the subclass of a class from a specific module.'''
        name = class_.__name__ + 'Sub'
        if hasattr(module, name):
            return getattr(module, name)
        else:
            return None


#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'utf-8'
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r"[\n\r\s]+")
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r"<!\[CDATA\[.*?\]\]>", re_.DOTALL)

# Change this to redirect the generated superclass module to use a
# specific subclass module.
CurrentSubclassModule_ = None

#
# Support/utility functions.
#


def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write('    ')


def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2


def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1


def quote_attrib(inStr):
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1


def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text


def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name, ))
    return value


class GDSParseError(Exception):
    pass


def raise_parse_error(node, msg):
    msg = '%s (element %s/line %d)' % (msg, node.tag, node.sourceline, )
    raise GDSParseError(msg)


class MixedContainer:
    # Constants for category:
    CategoryNone = 0
    CategoryText = 1
    CategorySimple = 2
    CategoryComplex = 3
    # Constants for content_type:
    TypeNone = 0
    TypeText = 1
    TypeString = 2
    TypeInteger = 3
    TypeFloat = 4
    TypeDecimal = 5
    TypeDouble = 6
    TypeBoolean = 7
    TypeBase64 = 8
    def __init__(self, category, content_type, name, value):
        self.category = category
        self.content_type = content_type
        self.name = name
        self.value = value
    def getCategory(self):
        return self.category
    def getContenttype(self, content_type):
        return self.content_type
    def getValue(self):
        return self.value
    def getName(self):
        return self.name
    def export(self, outfile, level, name, namespace,
               pretty_print=True):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                outfile.write(self.value)
        elif self.category == MixedContainer.CategorySimple:
            self.exportSimple(outfile, level, name)
        else:    # category == MixedContainer.CategoryComplex
            self.value.export(
                outfile, level, namespace, name,
                pretty_print=pretty_print)
    def exportSimple(self, outfile, level, name):
        if self.content_type == MixedContainer.TypeString:
            outfile.write('<%s>%s</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeInteger or \
                self.content_type == MixedContainer.TypeBoolean:
            outfile.write('<%s>%d</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeFloat or \
                self.content_type == MixedContainer.TypeDecimal:
            outfile.write('<%s>%f</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeDouble:
            outfile.write('<%s>%g</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeBase64:
            outfile.write('<%s>%s</%s>' % (
                self.name,
                base64.b64encode(self.value),
                self.name))
    def to_etree(self, element):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                if len(element) > 0:
                    if element[-1].tail is None:
                        element[-1].tail = self.value
                    else:
                        element[-1].tail += self.value
                else:
                    if element.text is None:
                        element.text = self.value
                    else:
                        element.text += self.value
        elif self.category == MixedContainer.CategorySimple:
            subelement = etree_.SubElement(
                element, '%s' % self.name)
            subelement.text = self.to_etree_simple()
        else:    # category == MixedContainer.CategoryComplex
            self.value.to_etree(element)
    def to_etree_simple(self):
        if self.content_type == MixedContainer.TypeString:
            text = self.value
        elif (self.content_type == MixedContainer.TypeInteger or
                self.content_type == MixedContainer.TypeBoolean):
            text = '%d' % self.value
        elif (self.content_type == MixedContainer.TypeFloat or
                self.content_type == MixedContainer.TypeDecimal):
            text = '%f' % self.value
        elif self.content_type == MixedContainer.TypeDouble:
            text = '%g' % self.value
        elif self.content_type == MixedContainer.TypeBase64:
            text = '%s' % base64.b64encode(self.value)
        return text
    def exportLiteral(self, outfile, level, name):
        if self.category == MixedContainer.CategoryText:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type,
                    self.name, self.value))
        elif self.category == MixedContainer.CategorySimple:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type,
                    self.name, self.value))
        else:    # category == MixedContainer.CategoryComplex
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s",\n' % (
                    self.category, self.content_type, self.name,))
            self.value.exportLiteral(outfile, level + 1)
            showIndent(outfile, level)
            outfile.write(')\n')


class MemberSpec_(object):
    def __init__(self, name='', data_type='', container=0,
            optional=0, child_attrs=None, choice=None):
        self.name = name
        self.data_type = data_type
        self.container = container
        self.child_attrs = child_attrs
        self.choice = choice
        self.optional = optional
    def set_name(self, name): self.name = name
    def get_name(self): return self.name
    def set_data_type(self, data_type): self.data_type = data_type
    def get_data_type_chain(self): return self.data_type
    def get_data_type(self):
        if isinstance(self.data_type, list):
            if len(self.data_type) > 0:
                return self.data_type[-1]
            else:
                return 'xs:string'
        else:
            return self.data_type
    def set_container(self, container): self.container = container
    def get_container(self): return self.container
    def set_child_attrs(self, child_attrs): self.child_attrs = child_attrs
    def get_child_attrs(self): return self.child_attrs
    def set_choice(self, choice): self.choice = choice
    def get_choice(self): return self.choice
    def set_optional(self, optional): self.optional = optional
    def get_optional(self): return self.optional


def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)

#
# Data representation classes.
#


class DATA_DATE(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, DATA_DATE)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if DATA_DATE.subclass:
            return DATA_DATE.subclass(*args_, **kwargs_)
        else:
            return DATA_DATE(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='DATA_DATE', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('DATA_DATE')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='DATA_DATE')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='DATA_DATE', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='DATA_DATE'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='DATA_DATE', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class DATA_DATE


class DEALER_BRANCH_ID(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, DEALER_BRANCH_ID)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if DEALER_BRANCH_ID.subclass:
            return DEALER_BRANCH_ID.subclass(*args_, **kwargs_)
        else:
            return DEALER_BRANCH_ID(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='DEALER_BRANCH_ID', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('DEALER_BRANCH_ID')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='DEALER_BRANCH_ID')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='DEALER_BRANCH_ID', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='DEALER_BRANCH_ID'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='DEALER_BRANCH_ID', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class DEALER_BRANCH_ID


class DEALER_ID(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, DEALER_ID)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if DEALER_ID.subclass:
            return DEALER_ID.subclass(*args_, **kwargs_)
        else:
            return DEALER_ID(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='DEALER_ID', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('DEALER_ID')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='DEALER_ID')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='DEALER_ID', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='DEALER_ID'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='DEALER_ID', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class DEALER_ID


class DEALER_SYSTEM(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, DEALER_SYSTEM)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if DEALER_SYSTEM.subclass:
            return DEALER_SYSTEM.subclass(*args_, **kwargs_)
        else:
            return DEALER_SYSTEM(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='DEALER_SYSTEM', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('DEALER_SYSTEM')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='DEALER_SYSTEM')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='DEALER_SYSTEM', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='DEALER_SYSTEM'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='DEALER_SYSTEM', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class DEALER_SYSTEM


class PART_STOCK(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, PART_STOCK_HEADER=None, PART_STOCK_DETAIL=None, PART_STOCK_CONTROL=None):
        self.original_tagname_ = None
        self.PART_STOCK_HEADER = PART_STOCK_HEADER
        if PART_STOCK_DETAIL is None:
            self.PART_STOCK_DETAIL = []
        else:
            self.PART_STOCK_DETAIL = PART_STOCK_DETAIL
        self.PART_STOCK_CONTROL = PART_STOCK_CONTROL
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, PART_STOCK)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if PART_STOCK.subclass:
            return PART_STOCK.subclass(*args_, **kwargs_)
        else:
            return PART_STOCK(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_PART_STOCK_HEADER(self): return self.PART_STOCK_HEADER
    def set_PART_STOCK_HEADER(self, PART_STOCK_HEADER): self.PART_STOCK_HEADER = PART_STOCK_HEADER
    def get_PART_STOCK_DETAIL(self): return self.PART_STOCK_DETAIL
    def set_PART_STOCK_DETAIL(self, PART_STOCK_DETAIL): self.PART_STOCK_DETAIL = PART_STOCK_DETAIL
    def add_PART_STOCK_DETAIL(self, value): self.PART_STOCK_DETAIL.append(value)
    def insert_PART_STOCK_DETAIL_at(self, index, value): self.PART_STOCK_DETAIL.insert(index, value)
    def replace_PART_STOCK_DETAIL_at(self, index, value): self.PART_STOCK_DETAIL[index] = value
    def get_PART_STOCK_CONTROL(self): return self.PART_STOCK_CONTROL
    def set_PART_STOCK_CONTROL(self, PART_STOCK_CONTROL): self.PART_STOCK_CONTROL = PART_STOCK_CONTROL
    def hasContent_(self):
        if (
            self.PART_STOCK_HEADER is not None or
            self.PART_STOCK_DETAIL or
            self.PART_STOCK_CONTROL is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='PART_STOCK', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('PART_STOCK')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='PART_STOCK')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='PART_STOCK', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='PART_STOCK'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='PART_STOCK', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.PART_STOCK_HEADER is not None:
            self.PART_STOCK_HEADER.export(outfile, level, namespace_, name_='PART_STOCK_HEADER', pretty_print=pretty_print)
        for PART_STOCK_DETAIL_ in self.PART_STOCK_DETAIL:
            PART_STOCK_DETAIL_.export(outfile, level, namespace_, name_='PART_STOCK_DETAIL', pretty_print=pretty_print)
        if self.PART_STOCK_CONTROL is not None:
            self.PART_STOCK_CONTROL.export(outfile, level, namespace_, name_='PART_STOCK_CONTROL', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'PART_STOCK_HEADER':
            obj_ = PART_STOCK_HEADER.factory()
            obj_.build(child_)
            self.PART_STOCK_HEADER = obj_
            obj_.original_tagname_ = 'PART_STOCK_HEADER'
        elif nodeName_ == 'PART_STOCK_DETAIL':
            obj_ = PART_STOCK_DETAIL.factory()
            obj_.build(child_)
            self.PART_STOCK_DETAIL.append(obj_)
            obj_.original_tagname_ = 'PART_STOCK_DETAIL'
        elif nodeName_ == 'PART_STOCK_CONTROL':
            obj_ = PART_STOCK_CONTROL.factory()
            obj_.build(child_)
            self.PART_STOCK_CONTROL = obj_
            obj_.original_tagname_ = 'PART_STOCK_CONTROL'
# end class PART_STOCK


class SUPP_CODE(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, SUPP_CODE)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if SUPP_CODE.subclass:
            return SUPP_CODE.subclass(*args_, **kwargs_)
        else:
            return SUPP_CODE(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='SUPP_CODE', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('SUPP_CODE')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='SUPP_CODE')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='SUPP_CODE', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='SUPP_CODE'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='SUPP_CODE', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class SUPP_CODE


class PART_NO(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, PART_NO)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if PART_NO.subclass:
            return PART_NO.subclass(*args_, **kwargs_)
        else:
            return PART_NO(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='PART_NO', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('PART_NO')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='PART_NO')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='PART_NO', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='PART_NO'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='PART_NO', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class PART_NO


class SESSION_ID(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, SESSION_ID)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if SESSION_ID.subclass:
            return SESSION_ID.subclass(*args_, **kwargs_)
        else:
            return SESSION_ID(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='SESSION_ID', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('SESSION_ID')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='SESSION_ID')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='SESSION_ID', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='SESSION_ID'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='SESSION_ID', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class SESSION_ID


class PART_STOCK_DETAIL(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, SUPP_CODE=None, DEALER_BRANCH_ID=None, PART_NO=None, QTY=None, UNIT_RRP=None, UNIT_AVG_COSTS=None):
        self.original_tagname_ = None
        self.SUPP_CODE = SUPP_CODE
        self.validate_SUPP_CODE(self.SUPP_CODE)
        self.DEALER_BRANCH_ID = DEALER_BRANCH_ID
        self.validate_DEALER_BRANCH_ID(self.DEALER_BRANCH_ID)
        self.PART_NO = PART_NO
        self.validate_PART_NO(self.PART_NO)
        self.QTY = QTY
        self.UNIT_RRP = UNIT_RRP
        self.UNIT_AVG_COSTS = UNIT_AVG_COSTS
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, PART_STOCK_DETAIL)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if PART_STOCK_DETAIL.subclass:
            return PART_STOCK_DETAIL.subclass(*args_, **kwargs_)
        else:
            return PART_STOCK_DETAIL(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_SUPP_CODE(self): return self.SUPP_CODE
    def set_SUPP_CODE(self, SUPP_CODE): self.SUPP_CODE = SUPP_CODE
    def get_DEALER_BRANCH_ID(self): return self.DEALER_BRANCH_ID
    def set_DEALER_BRANCH_ID(self, DEALER_BRANCH_ID): self.DEALER_BRANCH_ID = DEALER_BRANCH_ID
    def get_PART_NO(self): return self.PART_NO
    def set_PART_NO(self, PART_NO): self.PART_NO = PART_NO
    def get_QTY(self): return self.QTY
    def set_QTY(self, QTY): self.QTY = QTY
    def get_UNIT_RRP(self): return self.UNIT_RRP
    def set_UNIT_RRP(self, UNIT_RRP): self.UNIT_RRP = UNIT_RRP
    def get_UNIT_AVG_COSTS(self): return self.UNIT_AVG_COSTS
    def set_UNIT_AVG_COSTS(self, UNIT_AVG_COSTS): self.UNIT_AVG_COSTS = UNIT_AVG_COSTS
    def validate_SUPP_CODE(self, value):
        # Validate type SUPP_CODE, a restriction on xsd:string.
        pass
    def validate_DEALER_BRANCH_ID(self, value):
        # Validate type DEALER_BRANCH_ID, a restriction on xsd:string.
        pass
    def validate_PART_NO(self, value):
        # Validate type PART_NO, a restriction on xsd:string.
        pass
    def hasContent_(self):
        if (
            self.SUPP_CODE is not None or
            self.DEALER_BRANCH_ID is not None or
            self.PART_NO is not None or
            self.QTY is not None or
            self.UNIT_RRP is not None or
            self.UNIT_AVG_COSTS is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='PART_STOCK_DETAIL', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('PART_STOCK_DETAIL')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='PART_STOCK_DETAIL')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='PART_STOCK_DETAIL', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='PART_STOCK_DETAIL'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='PART_STOCK_DETAIL', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.SUPP_CODE is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sSUPP_CODE>%s</%sSUPP_CODE>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.SUPP_CODE), input_name='SUPP_CODE')), namespace_, eol_))
        if self.DEALER_BRANCH_ID is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sDEALER_BRANCH_ID>%s</%sDEALER_BRANCH_ID>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.DEALER_BRANCH_ID), input_name='DEALER_BRANCH_ID')), namespace_, eol_))
        if self.PART_NO is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sPART_NO>%s</%sPART_NO>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.PART_NO), input_name='PART_NO')), namespace_, eol_))
        if self.QTY is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sQTY>%s</%sQTY>%s' % (namespace_, self.gds_format_double(self.QTY, input_name='QTY'), namespace_, eol_))
        if self.UNIT_RRP is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sUNIT_RRP>%s</%sUNIT_RRP>%s' % (namespace_, self.gds_format_float(self.UNIT_RRP, input_name='UNIT_RRP'), namespace_, eol_))
        if self.UNIT_AVG_COSTS is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sUNIT_AVG_COSTS>%s</%sUNIT_AVG_COSTS>%s' % (namespace_, self.gds_format_float(self.UNIT_AVG_COSTS, input_name='UNIT_AVG_COSTS'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'SUPP_CODE':
            SUPP_CODE_ = child_.text
            SUPP_CODE_ = self.gds_validate_string(SUPP_CODE_, node, 'SUPP_CODE')
            self.SUPP_CODE = SUPP_CODE_
            # validate type SUPP_CODE
            self.validate_SUPP_CODE(self.SUPP_CODE)
        elif nodeName_ == 'DEALER_BRANCH_ID':
            DEALER_BRANCH_ID_ = child_.text
            DEALER_BRANCH_ID_ = self.gds_validate_string(DEALER_BRANCH_ID_, node, 'DEALER_BRANCH_ID')
            self.DEALER_BRANCH_ID = DEALER_BRANCH_ID_
            # validate type DEALER_BRANCH_ID
            self.validate_DEALER_BRANCH_ID(self.DEALER_BRANCH_ID)
        elif nodeName_ == 'PART_NO':
            PART_NO_ = child_.text
            PART_NO_ = self.gds_validate_string(PART_NO_, node, 'PART_NO')
            self.PART_NO = PART_NO_
            # validate type PART_NO
            self.validate_PART_NO(self.PART_NO)
        elif nodeName_ == 'QTY':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'QTY')
            self.QTY = fval_
        elif nodeName_ == 'UNIT_RRP':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'UNIT_RRP')
            self.UNIT_RRP = fval_
        elif nodeName_ == 'UNIT_AVG_COSTS':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'UNIT_AVG_COSTS')
            self.UNIT_AVG_COSTS = fval_
# end class PART_STOCK_DETAIL


class PART_STOCK_HEADER(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, SESSION_ID=None, DEALER_ID=None, DATA_DATE=None, DEALER_SYSTEM=None, EXTRACTION_DATE=None):
        self.original_tagname_ = None
        self.SESSION_ID = SESSION_ID
        self.validate_SESSION_ID(self.SESSION_ID)
        self.DEALER_ID = DEALER_ID
        self.validate_DEALER_ID(self.DEALER_ID)
        self.DATA_DATE = DATA_DATE
        self.validate_DATA_DATE(self.DATA_DATE)
        self.DEALER_SYSTEM = DEALER_SYSTEM
        self.validate_DEALER_SYSTEM(self.DEALER_SYSTEM)
        self.EXTRACTION_DATE = EXTRACTION_DATE
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, PART_STOCK_HEADER)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if PART_STOCK_HEADER.subclass:
            return PART_STOCK_HEADER.subclass(*args_, **kwargs_)
        else:
            return PART_STOCK_HEADER(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_SESSION_ID(self): return self.SESSION_ID
    def set_SESSION_ID(self, SESSION_ID): self.SESSION_ID = SESSION_ID
    def get_DEALER_ID(self): return self.DEALER_ID
    def set_DEALER_ID(self, DEALER_ID): self.DEALER_ID = DEALER_ID
    def get_DATA_DATE(self): return self.DATA_DATE
    def set_DATA_DATE(self, DATA_DATE): self.DATA_DATE = DATA_DATE
    def get_DEALER_SYSTEM(self): return self.DEALER_SYSTEM
    def set_DEALER_SYSTEM(self, DEALER_SYSTEM): self.DEALER_SYSTEM = DEALER_SYSTEM
    def get_EXTRACTION_DATE(self): return self.EXTRACTION_DATE
    def set_EXTRACTION_DATE(self, EXTRACTION_DATE): self.EXTRACTION_DATE = EXTRACTION_DATE
    def validate_SESSION_ID(self, value):
        # Validate type SESSION_ID, a restriction on xsd:string.
        pass
    def validate_DEALER_ID(self, value):
        # Validate type DEALER_ID, a restriction on xsd:string.
        pass
    def validate_DATA_DATE(self, value):
        # Validate type DATA_DATE, a restriction on xsd:string.
        pass
    def validate_DEALER_SYSTEM(self, value):
        # Validate type DEALER_SYSTEM, a restriction on xsd:string.
        pass
    def hasContent_(self):
        if (
            self.SESSION_ID is not None or
            self.DEALER_ID is not None or
            self.DATA_DATE is not None or
            self.DEALER_SYSTEM is not None or
            self.EXTRACTION_DATE is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='PART_STOCK_HEADER', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('PART_STOCK_HEADER')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='PART_STOCK_HEADER')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='PART_STOCK_HEADER', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='PART_STOCK_HEADER'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='PART_STOCK_HEADER', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.SESSION_ID is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sSESSION_ID>%s</%sSESSION_ID>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.SESSION_ID), input_name='SESSION_ID')), namespace_, eol_))
        if self.DEALER_ID is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sDEALER_ID>%s</%sDEALER_ID>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.DEALER_ID), input_name='DEALER_ID')), namespace_, eol_))
        if self.DATA_DATE is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sDATA_DATE>%s</%sDATA_DATE>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.DATA_DATE), input_name='DATA_DATE')), namespace_, eol_))
        if self.DEALER_SYSTEM is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sDEALER_SYSTEM>%s</%sDEALER_SYSTEM>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.DEALER_SYSTEM), input_name='DEALER_SYSTEM')), namespace_, eol_))
        if self.EXTRACTION_DATE is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sEXTRACTION_DATE>%s</%sEXTRACTION_DATE>%s' % (namespace_, self.gds_encode(self.gds_format_string(quote_xml(self.EXTRACTION_DATE), input_name='EXTRACTION_DATE')), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'SESSION_ID':
            SESSION_ID_ = child_.text
            SESSION_ID_ = self.gds_validate_string(SESSION_ID_, node, 'SESSION_ID')
            self.SESSION_ID = SESSION_ID_
            # validate type SESSION_ID
            self.validate_SESSION_ID(self.SESSION_ID)
        elif nodeName_ == 'DEALER_ID':
            DEALER_ID_ = child_.text
            DEALER_ID_ = self.gds_validate_string(DEALER_ID_, node, 'DEALER_ID')
            self.DEALER_ID = DEALER_ID_
            # validate type DEALER_ID
            self.validate_DEALER_ID(self.DEALER_ID)
        elif nodeName_ == 'DATA_DATE':
            DATA_DATE_ = child_.text
            DATA_DATE_ = self.gds_validate_string(DATA_DATE_, node, 'DATA_DATE')
            self.DATA_DATE = DATA_DATE_
            # validate type DATA_DATE
            self.validate_DATA_DATE(self.DATA_DATE)
        elif nodeName_ == 'DEALER_SYSTEM':
            DEALER_SYSTEM_ = child_.text
            DEALER_SYSTEM_ = self.gds_validate_string(DEALER_SYSTEM_, node, 'DEALER_SYSTEM')
            self.DEALER_SYSTEM = DEALER_SYSTEM_
            # validate type DEALER_SYSTEM
            self.validate_DEALER_SYSTEM(self.DEALER_SYSTEM)
        elif nodeName_ == 'EXTRACTION_DATE':
            EXTRACTION_DATE_ = child_.text
            EXTRACTION_DATE_ = self.gds_validate_string(EXTRACTION_DATE_, node, 'EXTRACTION_DATE')
            self.EXTRACTION_DATE = EXTRACTION_DATE_
# end class PART_STOCK_HEADER


class PART_STOCK_CONTROL(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, TOTAL_RECORDS=None, TOTAL_QTY=None, TOTAL_SOH_VALUE=None):
        self.original_tagname_ = None
        self.TOTAL_RECORDS = TOTAL_RECORDS
        self.TOTAL_QTY = TOTAL_QTY
        self.TOTAL_SOH_VALUE = TOTAL_SOH_VALUE
    def factory(*args_, **kwargs_):
        if CurrentSubclassModule_ is not None:
            subclass = getSubclassFromModule_(
                CurrentSubclassModule_, PART_STOCK_CONTROL)
            if subclass is not None:
                return subclass(*args_, **kwargs_)
        if PART_STOCK_CONTROL.subclass:
            return PART_STOCK_CONTROL.subclass(*args_, **kwargs_)
        else:
            return PART_STOCK_CONTROL(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_TOTAL_RECORDS(self): return self.TOTAL_RECORDS
    def set_TOTAL_RECORDS(self, TOTAL_RECORDS): self.TOTAL_RECORDS = TOTAL_RECORDS
    def get_TOTAL_QTY(self): return self.TOTAL_QTY
    def set_TOTAL_QTY(self, TOTAL_QTY): self.TOTAL_QTY = TOTAL_QTY
    def get_TOTAL_SOH_VALUE(self): return self.TOTAL_SOH_VALUE
    def set_TOTAL_SOH_VALUE(self, TOTAL_SOH_VALUE): self.TOTAL_SOH_VALUE = TOTAL_SOH_VALUE
    def hasContent_(self):
        if (
            self.TOTAL_RECORDS is not None or
            self.TOTAL_QTY is not None or
            self.TOTAL_SOH_VALUE is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='PART_STOCK_CONTROL', namespacedef_='', pretty_print=True):
        imported_ns_def_ = GenerateDSNamespaceDefs_.get('PART_STOCK_CONTROL')
        if imported_ns_def_ is not None:
            namespacedef_ = imported_ns_def_
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='PART_STOCK_CONTROL')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='PART_STOCK_CONTROL', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='PART_STOCK_CONTROL'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='PART_STOCK_CONTROL', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.TOTAL_RECORDS is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sTOTAL_RECORDS>%s</%sTOTAL_RECORDS>%s' % (namespace_, self.gds_format_float(self.TOTAL_RECORDS, input_name='TOTAL_RECORDS'), namespace_, eol_))
        if self.TOTAL_QTY is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sTOTAL_QTY>%s</%sTOTAL_QTY>%s' % (namespace_, self.gds_format_double(self.TOTAL_QTY, input_name='TOTAL_QTY'), namespace_, eol_))
        if self.TOTAL_SOH_VALUE is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sTOTAL_SOH_VALUE>%s</%sTOTAL_SOH_VALUE>%s' % (namespace_, self.gds_format_double(self.TOTAL_SOH_VALUE, input_name='TOTAL_SOH_VALUE'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'TOTAL_RECORDS':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'TOTAL_RECORDS')
            self.TOTAL_RECORDS = fval_
        elif nodeName_ == 'TOTAL_QTY':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'TOTAL_QTY')
            self.TOTAL_QTY = fval_
        elif nodeName_ == 'TOTAL_SOH_VALUE':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'TOTAL_SOH_VALUE')
            self.TOTAL_SOH_VALUE = fval_
# end class PART_STOCK_CONTROL


GDSClassesMapping = {
}


USAGE_TEXT = """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""


def usage():
    print(USAGE_TEXT)
    sys.exit(1)


def get_root_tag(node):
    tag = Tag_pattern_.match(node.tag).groups()[-1]
    rootClass = GDSClassesMapping.get(tag)
    if rootClass is None:
        rootClass = globals().get(tag)
    return tag, rootClass


def parse(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'xsd_double'
        rootClass = xsd_double
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     if not silence:
##         sys.stdout.write('<?xml version="1.0" ?>\n')
##         rootObj.export(
##             sys.stdout, 0, name_=rootTag,
##             namespacedef_='',
##             pretty_print=True)
    return rootObj


def parseEtree(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'xsd_double'
        rootClass = xsd_double
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    mapping = {}
    rootElement = rootObj.to_etree(None, name_=rootTag, mapping_=mapping)
    reverse_mapping = rootObj.gds_reverse_node_mapping(mapping)
##     if not silence:
##         content = etree_.tostring(
##             rootElement, pretty_print=True,
##             xml_declaration=True, encoding="utf-8")
##         sys.stdout.write(content)
##         sys.stdout.write('\n')
    return rootObj, rootElement, mapping, reverse_mapping


def parseString(inString, silence=False):
    if sys.version_info.major == 2:
        from StringIO import StringIO as IOBuffer
    else:
        from io import BytesIO as IOBuffer
    parser = None
    doc = parsexml_(IOBuffer(inString), parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'xsd_double'
        rootClass = xsd_double
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     if not silence:
##         sys.stdout.write('<?xml version="1.0" ?>\n')
##         rootObj.export(
##             sys.stdout, 0, name_=rootTag,
##             namespacedef_='')
    return rootObj


def parseLiteral(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'xsd_double'
        rootClass = xsd_double
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     if not silence:
##         sys.stdout.write('#from dsoh import *\n\n')
##         sys.stdout.write('import dsoh as model_\n\n')
##         sys.stdout.write('rootObj = model_.rootClass(\n')
##         rootObj.exportLiteral(sys.stdout, 0, name_=rootTag)
##         sys.stdout.write(')\n')
    return rootObj


def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()


if __name__ == '__main__':
    #import pdb; pdb.set_trace()
    main()


__all__ = [
    "DATA_DATE",
    "DEALER_BRANCH_ID",
    "DEALER_ID",
    "DEALER_SYSTEM",
    "PART_NO",
    "PART_STOCK",
    "PART_STOCK_CONTROL",
    "PART_STOCK_DETAIL",
    "PART_STOCK_HEADER",
    "SESSION_ID",
    "SUPP_CODE"
]
